"""Streamlit Judge Dashboard for Unified Recovery Engine (Milestone M8 Audit & Validation).

INVARIANTS:
1. PROMINENT SANDBOX MARKER: Clear visual indicators that all payment events, decisions, and execution outcomes are generated by deterministic sandbox simulation.
2. AUDITABLE DECISION TRACE: Complete end-to-end correlation trace from raw event to Stage 0/1, hard safety filters, AI decision, contact ledger, sandbox execution, reconciliation, and attribution.
3. CLEAR ATTRIBUTION DISTINCTION: Displays exact distinction between intervention-driven recovery (attributed > ₹0) and natural baseline self-cure (attributed = ₹0).
"""

import streamlit as st
import pandas as pd
from typing import Dict, Any, List
from app.domain.enums import ActionType, PaymentOutcome, StatisticalStatus, DecisionMode, SafetyRejectReason
from app.experiment.runner import ExperimentRunner
from app.experiment.feedback_loop import FeedbackLoopEngine
from app.sandbox.scenarios import GOLDEN_DEMO_SCENARIOS, ScenarioRunner, DemoScenarioSpec


def render_dashboard():
    """Render the interactive Streamlit Judge Dashboard."""
    st.set_page_config(
        page_title="Unified Recovery Engine — M8 Judge Audit Dashboard",
        page_icon="⚖️",
        layout="wide",
    )

    # 1. Header Banner & Safety Marker
    st.title("⚖️ Unified Recovery Engine — Judge Audit & Validation Dashboard")
    st.caption("Track 3 AI Revenue Recovery | Milestone M8 Production-Ready Audit Interface")

    st.error(
        "⚠️ **SANDBOX / SIMULATED PROTOYPE MODE** — "
        "No live Razorpay payment credentials, real money, or external gateway APIs are used. "
        "All payment failures, recovery recommendations, outreach deliveries, and payment outcomes are deterministic local sandbox simulations."
    )

    tabs = st.tabs([
        "🎯 Scenario Explorer & Trace",
        "📊 5-Arm Experiment Benchmark",
        "🔒 Safety Invariants & Contact Budget",
        "🔁 Retraining Dataset Inspector (INV-7)",
        "📖 System Architecture Guide",
    ])

    # =========================================================================
    # TAB 1: SCENARIO EXPLORER & END-TO-END TRACE
    # =========================================================================
    with tabs[0]:
        st.header("🎯 Judge Scenario Explorer & End-to-End Decision Trace")
        st.markdown(
            "Select any pre-configured Golden Demo Scenario to run it through the complete "
            "closed-loop orchestrator (Stage 0 Validation → Stage 1 Diagnosis → Candidate Generation → "
            "Hard Safety Filter → AI Decision Engine → Contact Budget Reservation → Sandbox Execution → "
            "Reconciliation → Attribution Engine)."
        )

        scenario_keys = list(GOLDEN_DEMO_SCENARIOS.keys())
        selected_key = st.selectbox(
            "Choose Golden Scenario to Execute:",
            options=scenario_keys,
            format_func=lambda k: GOLDEN_DEMO_SCENARIOS[k].title,
        )

        spec = GOLDEN_DEMO_SCENARIOS[selected_key]
        st.info(f"**Scenario Goal**: {spec.description}")

        col_s1, col_s2 = st.columns([1, 2])
        with col_s1:
            st.markdown("### Raw Payment Failure Event")
            st.json(spec.raw_event)
            if spec.simulate_outage_gateway:
                st.warning(f"Simulating Active Gateway Outage: **{spec.simulate_outage_gateway}**")
            if spec.exhaust_contact_budget_customer:
                st.warning(f"Exhausting Contact Budget for Customer: **{spec.exhaust_contact_budget_customer}**")
            if spec.force_sandbox_outcome:
                st.info(f"Forced Sandbox Outcome: **{spec.force_sandbox_outcome.value}**")

        runner = ScenarioRunner()
        result = runner.run_scenario(spec)

        with col_s2:
            st.markdown("### End-to-End Recovery Result Overview")
            r_col1, r_col2, r_col3, r_col4 = st.columns(4)
            with r_col1:
                st.metric("Selected Action", result.decision.selected_action.value)
            with r_col2:
                st.metric("Decision Mode", result.decision.decision_mode.value)
            with r_col3:
                st.metric("Simulated Outcome", result.attribution.payment_outcome.value)
            with r_col4:
                st.metric(
                    "AI-Attributed Recovery",
                    f"₹{result.attribution.attributed_recovered_paise / 100:,.2f}",
                    delta="₹0 (Self-Cure)" if result.attribution.attributed_recovered_paise == 0 else f"₹{result.attribution.gross_recovered_paise / 100:,.2f} Gross",
                )

        st.markdown("---")
        st.subheader("🔍 Complete Correlation Trace & Pipeline Inspection")

        # Visual pipeline steps
        t1, t2, t3, t4, t5, t6, t7 = st.tabs([
            "1. Opportunity (Stage 0/1)",
            "2. Candidates & Safety Filters",
            "3. AI Decision & Counterfactual",
            "4. Contact Ledger Reservation",
            "5. Sandbox Execution",
            "6. Reconciliation",
            "7. Attribution & Trace ID",
        ])

        with t1:
            st.markdown("#### Stage 0 Validation & Stage 1 Failure Diagnosis")
            col_a, col_b = st.columns(2)
            with col_a:
                st.write("**Opportunity ID**:", result.opportunity_id)
                st.write("**Merchant ID**:", result.merchant_id)
                st.write("**Customer ID**:", result.customer_id)
            with col_b:
                st.write("**Amount (Rupees)**:", f"₹{result.attribution.amount_at_risk_paise / 100:,.2f}")
                st.write("**Event ID**:", result.event_id)

        with t2:
            st.markdown("#### Candidate Action Generation & Hard Safety Filter Evaluation")
            cand_rows = []
            for c in result.decision.candidate_scores:
                cand_rows.append({
                    "Action Type": c.action_type.value,
                    "Eligibility": c.eligibility.value,
                    "P(Recovery | Action)": f"{c.raw_probability:.2%}",
                    "P(NO_ACTION)": f"{c.baseline_probability:.2%}",
                    "Incremental Uplift": f"{c.incremental_effect:+.2%}",
                    "Expected Value (₹)": f"₹{c.expected_value_paise / 100:,.2f}",
                    "Action Cost (₹)": f"₹{c.action_cost_paise / 100:,.2f}",
                    "Safety Reject Reason": c.reject_reason.value,
                })
            st.dataframe(pd.DataFrame(cand_rows), use_container_width=True)

        with t3:
            st.markdown("#### AI Decision Engine Evaluation (S-Learner Incremental EV)")
            d = result.decision
            st.json({
                "decision_id": d.decision_id,
                "model_version": d.model_version,
                "decision_mode": d.decision_mode.value,
                "selected_action": d.selected_action.value,
                "baseline_probability_no_action": d.baseline_probability,
                "selected_action_raw_probability": d.selected_action_score.raw_probability,
                "incremental_uplift": d.selected_action_score.incremental_effect,
                "expected_value_paise": d.selected_action_score.expected_value_paise,
                "abstention_reason": d.abstention_reason.value if d.abstention_reason else None,
                "provenance": d.provenance.value,
            })

        with t4:
            st.markdown("#### Contact Budget Arbitration (INV-2)")
            st.write("**Contact Reserved Status**:", f"✅ GRANTED" if d.is_contact_reserved else "❌ REJECTED / NOT REQUIRED")

        with t5:
            st.markdown("#### Sandbox Execution Outcome (Simulated)")
            if result.execution_result:
                st.json(result.execution_result.to_dict())
            else:
                st.write("No active intervention executed (NO_ACTION / Safe Abstention).")

        with t6:
            st.markdown("#### Reconciliation Ladder Status")
            rec_state = result.execution_result.execution_status.value if result.execution_result else "NONE"
            st.write("**Execution Status**:", rec_state)
            st.write("**Explanation**:", result.attribution.explanation)



        with t7:
            st.markdown("#### Attribution & Trace Correlation ID")
            st.success(f"**Correlation Trace ID**: `{result.trace_id}`")
            st.json(result.observation.to_dict())

    # =========================================================================
    # TAB 2: 5-ARM EXPERIMENT BENCHMARKING
    # =========================================================================
    with tabs[1]:
        st.header("📊 5-Arm Experimentation & Simulation Benchmarking (ADR-0011)")
        st.markdown(
            "Executes batch simulation across 5 pre-registered arms under identical event sequences "
            "using deterministic seeded randomization. Demonstrates primary metric evaluation (`A2 vs A1`) "
            "and Holm-Bonferroni secondary multiplicity control."
        )

        col_ex1, col_ex2 = st.columns([1, 3])
        with col_ex1:
            st.subheader("Benchmark Controls")
            seed_start = st.number_input("Start Seed", value=21, min_value=1)
            seed_end = st.number_input("End Seed", value=25, min_value=1)
            opp_count = st.number_input("Opportunities per Seed", value=10, min_value=5)

            if st.button("🚀 Run 5-Arm Benchmark"):
                seeds = list(range(int(seed_start), int(seed_end) + 1))
                events = [
                    {
                        "merchant_id": "merchant_alpha",
                        "customer_id": f"cust_{i % 5}",
                        "event_id": f"evt_bench_{i}",
                        "amount_paise": (1000 + (i * 500)) * 100,
                        "gateway": "HDFC" if i % 2 == 0 else "RAZORPAY",
                    }
                    for i in range(int(opp_count))
                ]
                runner = ExperimentRunner(experiment_id="EXP_M8_BENCHMARK")
                st.session_state["m8_summary"] = runner.run_paired_experiment(events=events, seeds=seeds)

        summary = st.session_state.get("m8_summary", None)
        with col_ex2:
            if summary:
                st.subheader("🎯 Primary Comparison Metric: A2 (Unified Engine) vs A1 (Independent Baseline)")
                p_comp = summary.primary_comparison

                c1, c2, c3, c4 = st.columns(4)
                c1.metric("Comparison", p_comp.comparison_id)
                c2.metric("Incremental Recovery Rate", f"{p_comp.incremental_recovery_rate:+.2%}", f"Relative: {p_comp.relative_lift:+.2%}")
                c3.metric("95% Confidence Interval", f"[{p_comp.confidence_interval_95[0]:.2%}, {p_comp.confidence_interval_95[1]:.2%}]")
                c4.metric("Statistical Verdict", p_comp.status.value)

                st.markdown(f"**Primary Verdict Detail**: {p_comp.explanation}")

                st.subheader("📊 5-Arm Summary Table")
                arm_rows = []
                for arm_name, metrics in summary.arm_metrics.items():
                    arm_rows.append({
                        "Arm": arm_name,
                        "Total Opps": metrics.total_opportunities,
                        "Recoveries": metrics.successful_recoveries,
                        "Recovery Rate": f"{metrics.recovery_rate:.2%}",
                        "Gross Recovered (₹)": f"₹{metrics.gross_recovered_paise / 100:,.2f}",
                        "AI Attributed (₹)": f"₹{metrics.attributed_recovered_paise / 100:,.2f}",
                        "Self-Cures": metrics.self_cured_count,
                        "Net Value (₹)": f"₹{metrics.net_value_paise / 100:,.2f}",
                    })
                st.dataframe(pd.DataFrame(arm_rows), use_container_width=True)

                st.subheader("🔍 Secondary Pairwise Comparisons (Holm-Bonferroni Corrected)")
                sec_rows = []
                for s in summary.secondary_comparisons:
                    sec_rows.append({
                        "Comparison": s.comparison_id,
                        "Incremental Rate": f"{s.incremental_recovery_rate:+.2%}",
                        "Gross Incremental (₹)": f"₹{s.gross_incremental_revenue_paise / 100:,.2f}",
                        "95% CI": f"[{s.confidence_interval_95[0]:.2%}, {s.confidence_interval_95[1]:.2%}]",
                        "p-value": s.p_value,
                        "Verdict": s.status.value,
                    })
                st.dataframe(pd.DataFrame(sec_rows), use_container_width=True)
            else:
                st.info("Click '🚀 Run 5-Arm Benchmark' to execute the experimentation suite.")

    # =========================================================================
    # TAB 3: SAFETY INVARIANTS & CONTACT BUDGET
    # =========================================================================
    with tabs[2]:
        st.header("🔒 Safety Invariants & Contact Budget Monitor")
        st.markdown("Verifies system safety invariants (`INV-1` through `INV-9`).")

        col_inv1, col_inv2 = st.columns(2)
        with col_inv1:
            st.markdown("### Architectural Safety Checklist")
            st.markdown("""
            - ✅ **INV-1 Tenant Isolation**: Multi-tenant customer & budget isolation.
            - ✅ **INV-2 Atomic Contact Reservation**: Conditional SQL budget reservation (`reserved + consumed < cap`).
            - ✅ **INV-3 Hard Safety Non-Overridability**: Gateway outages & budget limits cannot be overridden by AI exploration.
            - ✅ **INV-4 Gateway Outage Safety**: Active gateway outages suppress retry actions.
            - ✅ **INV-5 Retry Ownership**: Single active recovery process per opportunity.
            - ✅ **INV-6 Execution Unknown**: Ambiguous execution moves to reconciliation ladder.
            - ✅ **INV-7 Point-in-Time Features**: Post-decision outcome fields rejected from training feature vector $X$.
            - ✅ **INV-8 Self-Cure Attribution**: Uncontacted or natural self-cures receive strictly ₹0 AI attribution.
            - ✅ **INV-9 Counterfactual Baseline**: `NO_ACTION` counterfactual evaluated prior to candidate ranking.
            """)

        with col_inv2:
            st.markdown("### Interactive Outage Simulator")
            outage_gw = st.selectbox("Select Gateway for Outage Injection", ["HDFC", "ICICI", "RAZORPAY", "AXIS"])
            is_down = st.checkbox(f"Inject Outage for {outage_gw}", value=True)

            if st.button("Apply Outage Status"):
                runner = ScenarioRunner()
                runner.downtime_provider.set_outage(gateway_name=outage_gw, is_down=is_down)
                st.success(f"Outage status updated for {outage_gw}: is_down={is_down}")

    # =========================================================================
    # TAB 4: RETRAINING DATASET INSPECTOR
    # =========================================================================
    with tabs[3]:
        st.header("🔁 Point-in-Time Retraining Tuple Inspector (INV-7)")
        st.markdown(
            "Verifies transformation of `RecoveryObservation` records into clean point-in-time "
            "`TrainingRecord` tuples ($X, A, Y$) while guaranteeing zero post-decision feature leakage."
        )

        st.json({
            "denylisted_post_decision_fields": [
                "gross_recovered_paise",
                "attributed_recovered_paise",
                "self_cured",
                "payment_outcome",
                "outcome",
                "delivered_at",
                "outcome_timestamp",
            ],
            "enforcement_class": "app.scoring.feature_builder.PointInTimeLeakageError",
        })

    # =========================================================================
    # TAB 5: SYSTEM ARCHITECTURE GUIDE
    # =========================================================================
    with tabs[4]:
        st.header("📖 System Architecture & Judge Guide")
        st.markdown("""
        ### Core Principles
        1. **AI Role**: The AI does not recover money directly. It predicts incremental recovery probability $P(Y=1 | X, A) - P(Y=1 | X, \text{NO\_ACTION})$ and selects positive Expected Value interventions.
        2. **Self-Cure Rule**: Payments occurring without intervention delivery or under `NO_ACTION` are classified as `SELF_CURED` with **₹0 AI Attribution**.
        3. **Deterministic Sandbox**: Pure local Python 3.12.9 execution using SQLite WAL. No external paid APIs, cloud services, or production credentials required.
        """)


if __name__ == "__main__":
    render_dashboard()
